### DISCUSSION TITLE
registration not persistent across docker starts

### DISCUSSION THREAD

**Discussion by kevincw01** [bbernhard/signal-cli-rest-api#304] [Q&A] [answered]
I using the latest version as of today and I can successfully start the docker native using docker-compose yaml (see below).  I can also successfully register and send messages.  However when I stop the docker normal and start again, I get an error when I try to send a message that I am not registered.  The host path to is showing a mostly empty config file so I think there's a problem with the registration not being saved to the host config file but I'm not sure why.  Is there an api call I need to do to cause it to be persistent maybe?  I'd appreciate any tips.

contents of config file:
`cat /root/.local/share/signal-cli/data/accounts.json
{
  "accounts" : [ ],
  "version" : 2
}
`

permissions of config file and path:
```
ls -al /root/.local/share/
total 16
drwx------ 4 root   root   4096 Oct 30 14:38 .
drwxr-xr-x 3 root   root   4096 Oct 30 20:25 ..
drwx------ 2 root   root   4096 Oct 30 14:16 nano
drwxr-xr-x 3 ubuntu ubuntu 4096 Oct 30 14:46 signal-cli

ls -al /root/.local/share/signal-cli/data/
total 12
drwx------ 2 ubuntu ubuntu 4096 Oct 30 14:46 .
drwxr-xr-x 3 ubuntu ubuntu 4096 Oct 30 14:46 ..
-rw------- 1 ubuntu ubuntu   39 Oct 30 14:46 accounts.json

ls -al /root/.local/share/signal-cli/
total 12
drwxr-xr-x 3 ubuntu ubuntu 4096 Oct 30 14:46 .
drwx------ 4 root   root   4096 Oct 30 14:38 ..
drwx------ 2 ubuntu ubuntu 4096 Oct 30 14:46 data
```

docker compose yaml: 
```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "127.0.0.1:8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/root/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
```
