### DISCUSSION TITLE
Need help troubleshooting json-rpc mode + Home Assistant using received messages as triggers

### DISCUSSION THREAD

**Discussion by vloschiavo** [bbernhard/signal-cli-rest-api#361] [Q&A]
Greetings!  

I'm looking for help troubleshooting the Home Assistant integration (specifically, using received messages as automation triggers).

I have Home Assistant 2023.4.6 with the signal-cli-rest-api (v0.66.0) container installed as a Home Assistant Add-on running in json-rpc mode.  

**Home Assistant->phone works.**
Sending messages from Home Assistant to individuals or groups works fast and perfectly.  

**Phone-> Home Assistant doesn't work**
I'd like to be able to send a message from my users/phones to Home Assistant to use as a trigger - for example as a trigger to an automation.

I followed the setup instructions here: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md

I have the following in configuration.yaml (phone number redacted).
```
rest:
  - resource: "http://127.0.0.1:8080/v1/receive/+12125551212"
    headers:
      Content-Type: application/json
    sensor:
      - name: "Signal message received"
        value_template: "{{ value_json[0].envelope.dataMessage.message }}" #this will fetch the message
```

I can see in the container logs that the messages are being received by the signal-cli-rest-api:
```
...
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/data
time="2023-05-02T19:50:34-07:00" level=info msg="Started Signal Messenger REST API"
[GIN] 2023/05/02 - 19:50:41 | 400 |     139.425µs |     172.30.32.1 | GET      "/v1/receive/+12125551212"
[GIN] 2023/05/02 - 19:50:56 | 400 |      85.892µs |     172.30.32.1 | GET      "/v1/receive/+12125551212"
[GIN] 2023/05/02 - 19:51:11 | 400 |      73.319µs |     172.30.32.1 | GET      "/v1/receive/+12125551212"
```

I've also used wscat to verify the messages are coming in as intended and follow the expected json schema outlined in the 'rest' configuration above.

However, those received messages aren't triggering the automation:
```
alias: Test Signal Receive
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.signal_message_received
    to: Time
action:
  - service: notify.signal_me
    data:
      message: "{{ now() }}"
    enabled: true
mode: single
```

- The automation never gets triggered, so there are no traces to look at. 
- The home assistant logs don't show anything relating to "rest" or any errors on triggers or automations or anything else I can't explain.

Any suggestions on where to go from here before reaching out on r/homeassistant ?
