### DISCUSSION TITLE
Home Assistant - Changing from native mode to json-rpc

### DISCUSSION THREAD

**Discussion by Markus9955** [bbernhard/signal-cli-rest-api#530] [Q&A]
I have the docker container setup and running with home assistant and can send messages to Signal using notify and receive messages from signal using the rest interface. 

If I was to flip this over to the json-rpc mode what changes would I need to make to home assistant to be able to receive messages?

Hopefully its ok to post this here, if not then please delete this :-)

At the moment I have this config in my configuration.yaml and I'm assuming I need to change the rest interface over to one for websockets but at that point I run out of knowledge, skill and abilty: 

```
notify:
  - name: signal
    platform: signal_messenger
    url: "http://x.x.x.x:8080" # the URL where the Signal Messenger REST API is listening
    number: "<number>" # the sender number
    recipients: # one or more recipients
      - "<number>"

rest:
    - resource: "http://x.x.x.x:8080/v1/receive/<number>"
      headers:
        Content-Type: application/json
      sensor:
        - name: "Signal message received"
          unique_id: signal-message-rx
          value_template: >-
                {{ value_json[0].envelope.dataMessage.message }}
          json_attributes_path: $[0].envelope
          json_attributes:
            - source #using attributes you can get additional information, in this case, the phone number.
            - dataMessage #this contains the actual message and other useful information e.g. recipient (esp if group)
```
