### ISSUE TITLE
Send fails for multiple recipients

### ISSUE THREAD

**Issue by lein1013** [bbernhard/signal-cli-rest-api#105]
I use the homeassistant signal integration with the addon and tried the service with **ONE** single recipient - that works fine; 
BUT with **more** **NO** sms are sent (respectively, received by the recipeints)
call the service 
```
service: notify.signal2ABC
data: 
  message: test
```

in the homeassistant config
```
notify:
  - name: signal2A
    platform: signal_messenger
    url: "http://my.url:8081" # the URL where the Signal Messenger REST API is listening
    number: "+12346666" # the sender number
    recipients: # one or more recipients
      - "+12345678991" # A
  - name: signal2ABC
    platform: signal_messenger
    url: "http://my.url:8081" # the URL where the Signal Messenger REST API is listening
    number: "+12346666" # the sender number
    recipients: # one or more recipients
      - "+12345678991" # A
      - "+12345678992" # B
      - "+12345678993" # C
```
In the addon log I see
```
[GIN] 2021/03/07 - 23:09:00 | 400 | 11.351670723s |      10.x.x.xxx | POST     "/v2/send"
```
I tried it also via curl in the terminal 
```
curl -X GET -H "Content-Type: application/json" 'http://my.url:8081/v1/about'   
{"versions":["v1","v2"],"build":2}#   
                                                                                                       
curl -X POST -H "Content-Type: application/json" -d '{"message":"test","number":"+12346666","recipients":["+12345678991"]}' 'http://my.url:8081/v2/send'

➜  /config curl -X POST -H "Content-Type: application/json" -d '{"message":"test2","number":"+12346666","recipients":["+12345678991","+12345678992"]}' 'http://my.url:8081/v2/send'

{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}#      
```
Any ideas?
