### ISSUE TITLE
Cannot send messages

### ISSUE THREAD

**Issue by MatejKovacic** [bbernhard/signal-cli-rest-api#116]
I have installed Signal on a separate server. It is working, I can send messages with curl.

In HomeAssistan in `/config/configuration.yaml` I have

```
notify:
  - name: signal
    platform: signal_messenger
    url: "http://xx.xx.xx.xx:8080" # the URL where the Signal Messenger REST API is listening
    number: "+3xxxxxx" # the sender number
    recipients: # one or more recipients
      - "+3yyyyy"
```

Then I created an automation. This is the Yaml of the automation:

```
alias: Notification - door
description: 'Notification from door sensor'
trigger:
  - platform: state
    to: 'on'
    from: 'off'
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
condition: []
action:
  - service: notify.mobile_app_myphone
    data:
      message: Door opened.
      title: Door
  - service: notify.signal
  data:
    message: "Door opened."
mode: single
```

The problem is, I never receive Signal message. How to find out what is wrong? Are there any log files available?
