### ISSUE TITLE
New sample docker-compose.yml does not work

### ISSUE THREAD

**Issue by f45tb00t** [bbernhard/signal-cli-rest-api#125]
Hello Bernhard,

I set up a complete new system since switching from a Pi to a machine with more power. Now I wanted to install your docker image again but it does not work anymore with the new docker-compose.yml file you provide. The old one is still working.

Actually I don't get the point what is wrong. But I must say I don't work that often with docker. Your older example just worked out of the box. 

Do you have an idea whats wrong?

old_code:
```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host syste...
```

new_code:
```
version: "3"
services:
  signal-cli-rest-api:
    build: "."
    environment:
      - USE_NATIVE=0
      - PORT=8080
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
```

logs:
```
docker-compose -f /srv/docker/docker-compose.yml up
Building signal-cli-rest-api
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /srv/docker/Dockerfile: no such file or directory
ERROR: Service 'signal-cli-rest-api' failed to build : Build failed
```

Edit: I tried now something. I just added "image: bbernhard/signal-cli-rest-api:latest" to your code and now it works.

Cheers

fastboot
