### ISSUE TITLE
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

### ISSUE THREAD

**Issue by hannes2323** [bbernhard/signal-cli-rest-api#145]
### The problem

Hi,

I suddenly have a problem with not receiving messages from signal, I guess the messages are not getting send out.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

armv7

Using:
Rest-API to Signal-CLI Home Assistant add-on
Signal Messenger version: 0.41

Home Assistant:
 * core-2021.6.6
 * supervisor-2021.06.6
 * Home Assistant OS 6.1

Error message:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
await coro_or_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/notify/init.py", line 159, in _async_notify_message_service
await self.async_send_message(**kwargs)
File "/usr/src/homeassistant/homeassistant/components/notify/init.py", line 136, in async_send_message
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
raise ex
File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 83, in send_message
raise exc
File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 79, in send_message
raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

If I enter die docker-container and use signal-cli directly, messages do get send out (but with unusual high latency) and I receive them on my phone.

Any ideas?

Thanks in advance!

**Comment by bbernhard** [comment]
> pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

Looks like the REST API wrapper killed the `signal-cli` process, as sending the message took to long. At the moment, there's a hardcoded timeout of 60 seconds for every REST API request. i.e if the operation takes longer than 60 seconds, the REST API wrapper aborts the request and kills the corresponding `signal-cli` process. That's why it works when using `signal-cli` directly, but not with the REST API wrapper. 

Do you maybe have changed anything in your network that could have caused the high latency? Invoking `signal-cli` on an armv7 system is pretty slow and takes quite some time, but 60 seconds is unusually slow.

**Comment by hannes2323** [comment]
Thank you for your quick reply.

I did not change anything on my network - the communication between signal-cli and the REST API Wrapper is on the same machine (rapsberry).

I updated HomeAssistant to current patchlevel, maybe there is a problem? Is there a way to increase the 60 second timeout? Maybe the raspberry can not keep up since the latest patch, which leads to the timeout?

**Comment by bbernhard** [comment]
I've just pushed a new docker image for testing to dockerhub which allows to manually increase the timeout. In case you want to try it out, please use the docker image tag `bbernhard/signal-cli-rest-api:0.70-dev` in your `docker-compose.yml` file. The timeout can be increased by setting the env variable `SIGNAL_CLI_CMD_TIMEOUT` in your `docker-compose.yml` file.

e.g:
```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.70-dev
    environment:
      - USE_NATIVE=0
      - SIGNAL_CLI_CMD_TIMEOUT=120 #increases the timeout to 120 seconds
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * *
      - PORT=8080
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
```
