### ISSUE TITLE
Text encoding problem

### ISSUE THREAD

**Issue by ChrisB85** [bbernhard/signal-cli-rest-api#155]
### The problem

When I'm sending message that includes polish characters "Zażółć gęśląjażń" i receive something like this: 
![signal-2021-08-19-162223](https://user-images.githubusercontent.com/792899/130085810-6f50094c-cc54-4bcb-b9e9-3e9c92270388.jpeg)

Tested with Postman.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
That's strange. I've just tested it with curl and it works for me :thinking: 

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "Zażółć gęśląjażń", "number": "<my registered signal number>", "recipients": ["<recipient number>"]}' 'http://127.0.0.1:8080/v2/send'
```

Could you please give it another try with curl (just to rule out that Postman does something strange)

**Comment by ChrisB85** [comment]
One more thing I haven't mentioned: `/v2/send` endpoint returns `404 page not found`. `/v1/send` works, but the result is as above. Using curl does not change anything.

**Comment by bbernhard** [comment]
> One more thing I haven't mentioned: `/v2/send` endpoint returns `404 page not found`.

Are you sure that you are using the latest docker image?

Could you please post the output of `signal-cli --version`. That should give us an indication whether your docker image is up to date. You can obtain the version with:

* Run `docker ps` to find out the container id of the `signal-cli-rest-api` docker container
* Run `docker exec -it <container id> /bin/bash` to connect to the running docker container
* Execute `signal-cli --version`

**Comment by ChrisB85** [comment]
I'm using `bbernhard/signal-cli-rest-api:latest` which I downloaded today. `signal-cli --version` gives `signal-cli 0.6.5`.

**Comment by bbernhard** [comment]
Ok, that one is heavily outdated. You should get version `0.8.4.1`. 

Have you maybe accidentally pinned the version in your `docker-compose.yml` file?

**Comment by ChrisB85** [comment]
Here's my docker-compose.yml file:

```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - USE_NATIVE=0
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * *
      - PORT=8080
    ports:
      - "8089:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "/data/signal-cli-rest-api:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is
 registered
```

I have downloded it with signal-cli-rest-api repo, changed volume and port.
