### ISSUE TITLE
"Couldn't read contents of /home/.local/share/signal-cli/data"

### ISSUE THREAD

**Issue by dattito** [bbernhard/signal-cli-rest-api#169]
### The problem

I am getting this error every time I try to run your image in json-rpc mode.

Sample docker-compose.yml file.
```yaml
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc
    ports:
      - "8080:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" # Error also without linking a volume
```
I tried to run it on my Windows machine with docker-desktop as well as on the RPi4.

It seems like the error comes from src/scripts/jsonrpc2-helper.go.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

Because it seems like no other one has the problem I have, maybe it is possible that I made a mistake?
