### ISSUE TITLE
Location of "signal-cli-config" folder on host system when moving to AWS

### ISSUE THREAD

**Issue by alastairayliffe** [bbernhard/signal-cli-rest-api#279]
### The problem

Hi,

I'm able to run the docker in normal mode on AWS, and successfully register a phone number (thanks for your help on a previous issue :)...

When I push an update to change the mode to json-rpc on AWS, the docker is unable to find the signal-cli-config folder... 

I get the message -
`
Couldn't read contents of /home/.local/share/signal-cli/data. Is your phone number properly registered?
`

It runs fine locally in json-rpc mode, but fails when I push to AWS (with the above issue)...

I guess it may be something to do with the absolute/relative file path... But any help would be greatly appreciated!

This is my docker-compose file -

```
version: "3.8"
services:
  signal-cli-rest-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    networks:
      - public
      - private
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    volumes:
        - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered

networks:
  public:
  private:
```

and this is my docker file

`FROM bbernhard/signal-cli-rest-api:latest`

I've had to split out for the push to work with AWS.

Thanks again for all your help :)...

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64
