### ISSUE TITLE
usermod UID already exists

### ISSUE THREAD

**Issue by william-bohannan** [bbernhard/signal-cli-rest-api#397]
### The problem

Running on kubernetes with a mount NFS share for the storage.  
1. NFS uses the uid/gid of 65534 (nobody/nogroup). 
2. Updated deployment to have the uid/gid of the NFS

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: signal-1
  labels:
    app: signal-1
spec:
  # multiple pods
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: signal-1
  template:
    metadata:
      labels:
        app: signal-1
    spec:
      restartPolicy: Always
      containers:
        - name: signal-cli-rest-api
          image: bbernhard/signal-cli-rest-api:latest
          # securityContext:
          #   runAsUser: 0
          #   runAsGroup: 0
          env:
          - name: MODE
            value: "native"     
          - name: SIGNAL_CLI_CONFIG_DIR
            value: "/data/store"              
          - name: SIGNAL_CLI_UID
            value: "65534"
          - name: SIGNAL_CLI_GID
            value: "65534"
          ports:
            - containerPort: 8080
              protocol: TCP           
          volumeMounts:
            - name: volume-nfs
              mountPath: /data/store
              subPath: data/clients/rainbow/signal-1
      volumes:
      - name: volume-nfs
        nfs:
          server: control1
          path: /nfs
```
3. Issue now is pod is looping when trying to create 65534 as already exists.
```
+ set -e
+ [ -z /home/.local/share/signal-cli ]
+ usermod -u 65534 signal-api
usermod: UID '65534' already exists
+ set -e
+ [ -z /home/.local/share/signal-cli ]
+ usermod -u 65534 signal-api
usermod: UID '65534' already exists
```
Tried running the pod as root, same result.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64
