### ISSUE TITLE
INFO message injected in JSON response

### ISSUE THREAD

**Issue by k-bx** [bbernhard/signal-cli-rest-api#407]
### The problem

<img width="858" alt="image" src="https://github.com/bbernhard/signal-cli-rest-api/assets/107968/9ee7c1d3-1124-46e5-aaa6-96cb1fafd317">

Upon receiving a batch of messages, sometimes I get JSON which also contains an INFO message like this:

INFO  IncomingMessageHandler - Ignoring a group message from an unauthorized sender (no member or admin)

which makes the JSON invalid.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Thanks, I'll have a look!

**Comment by kxait** [comment]
Hi, having the same issue here on the `/v1/receive` endpoint, additionally, the response for a `/v2/send` request fails with 400 and error message
```{"error":"strconv.ParseInt: parsing \"INFO  SignalAccount - Config file is in use by another instance, waiting…\\nINFO  SignalAccount - Config file lock acquired.\\n1696717441700\": invalid syntax"}```
even though the message is actually sent

**Comment by bbernhard** [comment]
> Hi, having the same issue here on the `/v1/receive` endpoint, additionally, the response for a `/v2/send` request fails with 400 and error message `{"error":"strconv.ParseInt: parsing \"INFO SignalAccount - Config file is in use by another instance, waiting…\\nINFO SignalAccount - Config file lock acquired.\\n1696717441700\": invalid syntax"}` even though the message is actually sent
> 
> This problem occurs on 0.69, but 0.67 works fine

That sounds like a different error. Do you have multiple signal-cli-rest-api docker containers running?

**Comment by kxait** [comment]
> That sounds like a different error. Do you have multiple signal-cli-rest-api docker containers running?

nope, definitely had only one instance running

**Comment by Herbs851** [comment]
Hi @bbernhard @kxait,

I've seen these errors in two cases with Home Assistant : 

1.  If you use a notification group instead of sending a message to a signal group : 

Ko with "platform group" like : 

```
notify:

  - name: Signal foo
    platform: signal_messenger
    url: !secret sigurl
    number: !secret signum
    recipients: !secret sigfoo

  - name: Signal bar
    platform: signal_messenger
    url: !secret sigurl
    number: !secret signum
    recipients: !secret sigbar

  - name: group_notif
    platform: group
    services:
      - service: signal_foo
      - service: signal_bar
```

I think that in this case HA makes 2 requests too quickly.

I fixed the error by creating a group signal directly, end then replace my old group by : 

```
notify:

  - name: group_signal
    platform: signal_messenger
    url: !secret sigurl
    number: !secret signum
    recipients: !secret id_grp_signal 
```

2. The second case, when an automation spams the api with a few messages too quickly.

That's what I've noticed.
