### ISSUE TITLE
'Is the number properly registered?' error in json-rpc mode

### ISSUE THREAD

**Issue by Kariton** [bbernhard/signal-cli-rest-api#440]
### The problem

After upgrading to v0.70 my signal service stopped working.
So i thought it might be some "fuckup" and removed all data and started completely fresh.

start docker in native mode
```docker run -p 8080:8080 --name signal-docker-native-v0.70 -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=native' bbernhard/signal-cli-rest-api:0.70```

register device on
http://localhost:8080/v1/qrcodelink?device_name=my-api-0.70

restart docker in json-rpc mode:
```docker run -p 8080:8080 --restart=always --name signal-docker-json-v0.70 -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=json-rpc' bbernhard/signal-cli-rest-api:0.70```

log gives me:
```
level=info msg="Found number  and added it to jsonrpc2.yml"
level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
```

swagger returns:
```
{
  "error": "Number not registered with JSON-RPC"
}
```

This is what i experience since i upgraded to v0.70.
but @Kuhkaefer mentioned the same issue here: https://github.com/bbernhard/signal-cli-rest-api/issues/435#issuecomment-1790686756

i think the problematic part is right here: "Found number "**DOUBLE SPACE**" and added it to jsonrpc2.yml"
IIRC it should look like: "Found number "**SPACE**" +123456789 "**SPACE**" and added it to jsonrpc2.yml"

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

the `jsonrpc2.yml` does also look wrong.
```
# cat $HOME/.local/share/signal-cli/jsonrpc2.yml
config:
  "":
    tcp_port: 6000
    fifo_pathname: /tmp/sigsocket0
```

IIRC this would be right:
```
# cat $HOME/.local/share/signal-cli/jsonrpc2.yml
config:
  "+123456789":
    tcp_port: 6000
    fifo_pathname: /tmp/sigsocket0
```

EDIT: added additional information
