### ISSUE TITLE
Port mapping problem

### ISSUE THREAD

**Issue by mp-mba** [bbernhard/signal-cli-rest-api#48]
Hi,

I wanted to run the docker on my Synology NAS using different port than 8080:

```
version: "3"
services:
  signal-cli-rest-api:
    container_name: signal-cli-rest-api
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8090:8090"
    volumes:
      - "/volume1/docker/signal-cli-rest-api/signal-cli-config:/home/.local/share/signal-cli"
    restart: always
```
![image](https://user-images.githubusercontent.com/20967500/104106459-50ea7400-52b6-11eb-9959-894cf4c42127.png)

But I see this in docker logs:
![image](https://user-images.githubusercontent.com/20967500/104106449-43cd8500-52b6-11eb-98d5-058ccd2b4978.png)

Am I doing something wrong?

**Comment by redwoodtree** [comment]
You're configuring your synology correctly and that error message is unrelated to any issues you may be having.

I'm running on Synology as well, same config as yours (different port) and I get the same message, I don't think that message is indicating a problem.  It's working just fine over here.  If you're unable to bring it up or connect to tit, maybe check any firewall you may have on that's blocking ports?

<img width="892" alt="Screen Shot 2021-01-09 at 11 17 54 AM" src="https://user-images.githubusercontent.com/1458885/104106783-a306a780-526c-11eb-9e40-809fb1d614dc.png">
<img width="507" alt="Screen Shot 2021-01-09 at 11 16 36 AM" src="https://user-images.githubusercontent.com/1458885/104106784-a437d480-526c-11eb-827c-087edeac3078.png">

**Comment by mp-mba** [comment]
@redwoodtree 
What if I need to run it on different port then 8080?

**Comment by bbernhard** [comment]
It should work like this:

```
version: "3"
services:
  signal-cli-rest-api:
    container_name: signal-cli-rest-api
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - PORT=8090
    ports:
      - "8090:8090"
    volumes:
      - "/volume1/docker/signal-cli-rest-api/signal-cli-config:/home/.local/share/signal-cli"
    restart: always
 ```
