### ISSUE TITLE
Container Size Grows

### ISSUE THREAD

**Issue by cyb3rg3cko** [bbernhard/signal-cli-rest-api#606]
### The problem

I have been running this for a couple of years with no issues. First and foremost I would like to thank you for your work. About a week ago i stopped receiving my messages and it was due to the container size growing so large that the sd card I run it on (in an Nvidia Jetson Nano) ran out of space. After using "ls -l" on the root directory from the console in portainer, I noticed the TMP folder had grown to 42 gigs. Can anyone advise on what the sqlite documents stored in there are, if it is ok to delete them, and how I can prevent this in the future. Thanks

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
Do you mean the `/tmp` folder inside the docker container or on the host system?

**Comment by bbernhard** [comment]
Do you often send messages with attachments? 

The only thing that `/tmp` is used for is for temporarily storing the attachments, but they should be removed immediately after the message was sent.

Could you maybe have a deeper look at what is stored there. Are there a lot of small files or a few bigger ones? Also the creation timestamp of those files would be interesting. As `/tmp` is just a temporary directory, it should get deleted every time you restart the docker container. So if you are at the latest release, which was ~3 weeks ago, that means 42GB of data has accumulated over 3 weeks - which is a lot. So either something grows really fast or there are some files in there which are older than 3 weeks.

**Comment by cyb3rg3cko** [comment]
I don't use attachments in it's current use. It only ever messages me so I don't think there is a case where attachments are being sent to another user. It is using latest, released 3 weeks ago but also doesn't appear to delete after a restart of the container (I just tested a restart of the whole machine).

**Comment by bbernhard** [comment]
Do you maybe have mounted the `/tmp` folder inside the container to some folder on the host system?

**Comment by cyb3rg3cko** [comment]
I don't believe so, everything is run from a docker compose listed below, there are several systems that work together but the only one that interacts with the signal docker is NodeRed.

```
services:
  ami_nodered:
    container_name: ami_nodered_09242023
    image: nodered/node-red
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
    - 1880:1880
    stdin_open: true
    tty: true
    environment:
      TZ: America/New_York
    volumes:
    - /home/ami/Apps/AMI/:/AMI
    - /home/ami/Apps/AMI/DockerConfigs/NodeRED/node_red_data:/data
  
  mysrv:
    container_name: ami_eclipse-mosquitto_09242023
    image: eclipse-mosquitto
    user: "${UID}:${GID}"
    restart: unless-stopped    
    ports:
    - 1883:1883
    - 9001:9001
    stdin_open: true
    tty: true
    environment:
      TZ: America/New_York
    volumes:
    - /home/ami/Apps/AMI/DockerConfigs/MosquittoMQTT/mosquitto:/mosquitto  
    - /home/ami/Apps/AMI/DockerConfigs/MosquittoMQTT/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - /mosquitto/data
    - /mosquitto/log     
    
  rhasspy:
    container_name: ami_rhasspy_09242023
    image: synesthesiam/rhasspy-server:latest
    user: "${UID}:${GID}"
    restart: unless-stopped    
    ports:
      - 12101:12101
    environment:
      TZ: America/New_York
    devices:
      - /dev/snd:/dev/snd
    command: --profile en --user-profiles /profiles      
    volumes:
      - /home/ami/Apps/AMI/:/AMI
      - /home/ami/Apps/AMI/DockerConfigs/Rhasspy:/rhasspy
      - /rhasspy/profiles:/profiles

  signal-cli-rest-api:
    container_name: ami_signal_09242023
    image: bbernhard/signal-cli-rest-api:latest
    user: "${UID}:${GID}"
    restart: unless-stopped   
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
    ports:
      - 8080:8080
    volumes:
      - /home/ami/Apps/AMI/DockerConfigs/Signal-CLI_Rest:/home/.local/share/signal-cli
      
version: '3'
```

**Comment by bbernhard** [comment]
that looks okay I'd say. 

Did you already check that:

> Could you maybe have a deeper look at what is stored there. Are there a lot of small files or a few bigger ones? Also the creation timestamp of those files would be interesting.

**Comment by cyb3rg3cko** [comment]
I used `ls -lh > /home/.local/share/signal-cli/Filelist.txt` to export the file list to my docker config Share directory. It looks like there are about 5300 files, 3300 are roughly 12mb large and the rest are 1.1mb or smaller. All files have signal-api as owner, date are all over the place. larger files follow the naming scheme "10000044319032255755libsignal_jni.so" smaller files follow the naming scheme "sqlite-3.44.0.0-000ee3b2-90b5-4d10-8a49-ecf533e3168d-libsqlitejdbc.so". I have attached the filelist.
[Filelist.txt](https://github.com/user-attachments/files/17496963/Filelist.txt)

**Comment by cyb3rg3cko** [comment]
I have attached another list filtered by dates using `ls -lh -t > /home/.local/share/signal-cli/Filelist.txt`, may make it easier to read. I looked and noticed i hadn't gotten a message since Oct 16th until i cleared room on the sd card by deleting some un-needed apps this morning. Other than that date I cant really find any significance to other dates when files were created.

[FilelistDates.txt](https://github.com/user-attachments/files/17497010/FilelistDates.txt)

**Comment by bbernhard** [comment]
Those look like temporary files created by signal-cli. I think it should be fine to delete those files (maybe make a backup of your SD card before doing that). But I still find it odd that those files don't get deleted when you restart the container...that's definitely weird.

**Comment by cyb3rg3cko** [comment]
Ok. I may make a script to make sure they get deleted at startup. If I do, I'll post it here. Thanks for your help

**Comment by cyb3rg3cko** [comment]
Just to close this out, below is a script I created that will delete everything in the `/tmp` that is not from the current day. 

```
#!/bin/bash
#This script is used to delete all files in the /tmp directory that aren't from the current date

# Get current date in YYYY-MM-DD format
current_date=$(date +%Y-%m-%d)

# Find and delete files in /tmp that do not match the current date
find /tmp -type f ! -newermt "$current_date" -delete

# Optional: Delete empty directories after removing old files
# find /tmp -type d -empty -delete
```

I used the following step to install and run the script
1) Created a file named clean_tmp.sh and pasted the above code into it
2) Since i bind the host directory `/home/ami/Apps/AMI/DockerConfigs/Signal-CLI_Rest` to the container directory `/home/.local/share/signal-cli` in my docker compose, I just copied the file to the host directory and made sure it had executable rights using `sudo chmod +x clean_tmp.sh` 
3) To launch on container start I added a command to call it from the container directory. `command: /home/.local/share/signal-cli/clean_tmp.sh` to the signal-cli-rest-api portion of my docker compose file. It now looks like this...

 ```
 signal-cli-rest-api:
    container_name: ami_signal_09242023
    image: bbernhard/signal-cli-rest-api:latest
    user: "${UID}:${GID}"
    restart: unless-stopped   
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
    ports:
      - 8080:8080
    volumes:
      - /home/ami/Apps/AMI/DockerConfigs/Signal-CLI_Rest:/home/.local/share/signal-cli
    command: /home/.local/share/signal-cli/clean_tmp.sh  
```
