### ISSUE TITLE
JSON-RPC: Specified account does not exist

### ISSUE THREAD

**Issue by DEV2DEV-DE** [bbernhard/signal-cli-rest-api#628]
### The problem

Since yesterday, i receive an error 'Specified account does not exist' when trying to send by json-rpc.
It has worked as expected until Dec 5th. There have been no changes since.
Still using the same image (from Oct 4th).

When using the cli in the docker console, i get
```
root@1f5d487884c2:/# signal-cli version
signal-cli 0.13.7
root@1f5d487884c2:/# signal-cli receive
No local users found, you first need to register or link an account
```
Here's the compose I'm using:
```
services:
  signal-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: Signal-REST-Api
    ports:
      - "8086:8080"
    volumes:
      - signal-api:/home/.local/share/signal-cli
    restart: unless-stopped
    environment:
      MODE: "json-rpc"

volumes:
  signal-api:
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64
