### ISSUE TITLE
Unable to register phone:

### ISSUE THREAD

**Issue by paquitoloco** [bbernhard/signal-cli-rest-api#650]
### The problem

I'm user Docker Portainer and the stack is working correctly:

```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-api
    environment:
      - MODE=native
    ports:
      - "8080:8080"
    volumes:
      - "/milocation/data/signal-cli:/home/.local/share/signal-cli"
    restart: unless-stopped
```

However, when entering the following:

`curl -X POST -H "Content-Type: application/json" -d '{"captcha":"captcha.........", "use_voice": false}' 'http://192.168.x.xx:8080/v1/register/+3xxx'`

I get the following error:

`{"error":"Failed to register: StatusCode: 429 (RegistrationRetryException)\n"}
`
Maybe I use the wrong captcha. The captcha has the following format:

signalcaptcha://signal-hcaptcha-short.5...

Under so I assume I have to use:

`curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signal-hcaptcha-short.5", "use_voice": false}' 'http://192.168.x.xx:8080/v1/register/+3xxx'`

However I am stuck with this:

`Failed to register: StatusCode: 429
`
Any ideas?

Thanks for your help.

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64
