### ISSUE TITLE
Add global variable to set `text_mode`

### ISSUE THREAD

**Issue by GAS85** [bbernhard/signal-cli-rest-api#671]
### Feature Request

Hello! Based on https://github.com/home-assistant/core/issues/117554 I would like to request global variable that user can set e.g. in compose file and control `text_mode` behavior. E.g. set it to `styled`.

My suggestion would be `SIGNAL_TEXT_MODE=styled` should enable all messages with `text_mode: styled` and if not provided or wrongly set, it shall be `text_mode: normal`. This will ensure integration like Home Assistant can use markdown as well.

**Comment by bbernhard** [comment]
With the next release it will be possible to set the default text mode with the env variable `DEFAULT_SIGNAL_TEXT_MODE`

**Comment by GAS85** [comment]
Hey, I do set it, but all messages from the Home Assistant are without any markdown.

```yaml
  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    restart: unless-stopped
    container_name: signal-cli
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal
      - SIGNAL_CLI_CONFIG_DIR=/home/.local/share/signal-cli/
      - DEFAULT_SIGNAL_TEXT_MODE=styled
      - SIGNAL_CLI_UID=${PUID}
      - SIGNAL_CLI_GID=${PGID}
      - LOG_LEVEL=info
    volumes:
      - ${WORKINGDIR}/docker/signal-cli:/home/.local/share/signal-cli
    healthcheck:
      test: curl -f http://localhost:8080/v1/health || exit 1
      interval: 5m00s
      timeout: 5s
      retries: 2
      start_period: 30s
    labels:
      - autoheal=true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
```
