### ISSUE TITLE
Sending messages fails with http status 400. "User +4915712345678 is not registered"

### ISSUE THREAD

**Issue by DEV2DEV-DE** [bbernhard/signal-cli-rest-api#696]
### The problem

It worked until Wednesday without any changes (as far as I know).
The host and the container have not changed.
Here's the debug output:
```
time="2025-05-03T21:57:08Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
time="2025-05-03T21:57:08Z" level=debug msg="*) docker exec -it / /bin/bash"
time="2025-05-03T21:57:08Z" level=debug msg="*) su signal-api"
time="2025-05-03T21:57:08Z" level=debug msg="*) echo 'Test' | signal-cli-native --config /home/.local/share/signal-cli -a +4915712345678 send --message-from-stdin +491721234567 --notify-self"
time="2025-05-03T21:57:09Z" level=debug msg="signal-cli output (stdout): "
time="2025-05-03T21:57:09Z" level=debug msg="signal-cli output (stderr): User +4915712345678 is not registered.\n"
Z[GIN] 2025/05/03 - 21:57:09 | 400 |  479.612347ms |   192.168.178.9 | POST     "/v2/send"
```
This is my Portainer-Stack:
```
services:
  signal-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: Signal-REST-Api
    ports:
      - "8086:8080"
    volumes:
      - signal-api:/home/.local/share/signal-cli
    restart: unless-stopped
    environment:
      MODE: "json-rpc"

volumes:
  signal-api:
```
Already re-started the container and forced a stack update - with no success.
Complete reboot of the host does not solve the problem anyway.

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
looks like an upstream issue:

https://github.com/AsamK/signal-cli/issues/1762

**Comment by GAS85** [comment]
Got the same issue, have to register my phone again via signal-cli, then it works fine.

**Comment by fivemeyestore** [comment]
Great implementation of this feature. I particularly like the approach to error handling.

**Comment by myeyestore** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by fivemhostingserver** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by eyesaider** [comment]
Very clean code with good test coverage. This is a great example of best practices.

**Comment by eyestorefivem** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by eyesgodcode** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by eyestoreoye** [comment]
I'm impressed by the modularity of this codebase. Makes it very maintainable.

**Comment by fivemserverhostings** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by eyestorefivemstore** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by fivemservereyestore** [comment]
Interesting solution to this problem! I've been working on similar challenges recently.

**Comment by fivemeyestoreserver** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by scriptforfivem** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by GAS85** [comment]
Bots getting crazy.

**Comment by DEV2DEV-DE** [comment]
I've switched to Pushover to send informations from my application. 
I'm tired of having to reset it every few months.

**Comment by f2calv** [comment]
I am running the v0.94 container in normal mode on Kubernetes (Microk8s) on a Raspberry Pi 5 16GB and had exactly this problem, it worked fine for years then stopped working with the "User XXX is not registered" regardless of the number of times I linked/unlinked my phone number.

Turns out I had added too restrictive Resource limits (memory/CPU) on the pod and starved it of resources, so it occasionally OOMKilled the whole pod or just performed very very slowly upon linking or sending (ultimately failed to send anything).

I increased the memory and CPU thresholds and everything worked just fine as it had for years before, doh!

FYI - here is the my full configuration with working Resource limits;

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalcli
  namespace: monitoring
  labels:
    app: signalcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signalcli
  template:
    metadata:
      labels:
        app: signalcli
    spec:
      containers:
        - name: primary
          image: bbernhard/signal-cli-rest-api:0.94
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MODE
              value: normal #slowest perf, normal memory
            # - name: MODE
            #   value: native #medium perf, normal memory
            # - name: MODE
            #   value: json-rpc #fastest perf, increased memory
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 100m
              memory: 196Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: signalcli
  namespace: monitoring
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: signalcli
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signalcli-ing
  namespace: monitoring
spec:
  rules:
    - host: signalcli.rp4
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: signalcli
              port:
                number: 80
```
