### ISSUE TITLE
This person is no longer using Signal

### ISSUE THREAD

**Issue by lug-gh** [bbernhard/signal-cli-rest-api#698]
Hey, I don't think it's a problem with the software, but maybe someone here can help or give me a tip anyway.

I've been using the signal rest api for a few years now, and since April 29th I've stopped receiving messages, unfortunately I only got around to looking at it today. It seems that my signal account of the sending number has been closed, when I go to the chat it says: `This person is no longe using Signal. Invite them to Signal to keep the conversation here.`

Has anyone else had this problem? I would first try to re-register the number, but I find it strange that the account was deleted by Signal.

This is my docker compose:
```
services:
  signal-cli-rest-api:
    container_name: signal-api
    restart: always
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - './data:/home/.local/share/signal-cli'
    environment:
      - MODE=json-rpc
    image: bbernhard/signal-cli-rest-api:latest-stable
```
