### ISSUE TITLE
QR Code Generation Failing

### ISSUE THREAD

**Issue by barndawgie** [bbernhard/signal-cli-rest-api#707]
### The problem

I am starting from scratch with an empty signal-api folder and the following `compose.yaml`:
```yaml
name: signal-api
services:
  signal-cli-rest-api:
      container_name: signal-api
      restart: unless-stopped
      ports:
          - 9922:8080
      volumes:
          - $VOLUME_BASE/signal-api:/home/.local/share/signal-cli
      image: bbernhard/signal-cli-rest-api
```

When I start this and visit `http://192.168.1.6:9922/v1/qrcodelink?device_name=signal-ap`, I get the following:
```json
{
error: "Couldn't create QR code: no data to encode"
}
```

My `/v1/about` shows the following:
```json
{
versions: [
"v1",
"v2"
],
build: 2,
mode: "normal",
version: "0.93",
capabilities: {
v2/send: [
"quotes",
"mentions"
]
}
}
```

Any ideas what is up?

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

I get the same result in `native` mode. `json-rpc` mode gives me a different error, `write tcp 127.0.0.1:45860->127.0.0.1:6001: write: broken pipe"`
