### ISSUE TITLE
Plugin `handlers are already registered for path`

### ISSUE THREAD

**Issue by Kariton** [bbernhard/signal-cli-rest-api#716]
### The problem

Hey,

i tried to use the plugin feature but encounter this error:
```
time="2025-06-25T10:17:57Z" level=info msg="Started Signal Messenger REST API"
panic: handlers are already registered for path '/v1/plugins/my-custom-send-endpoint/:number'
goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0x1123c59?, {0xc0002a6180, 0x2b}, {0xc0002a2030, 0x3, 0x3})
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/tree.go:260 +0x6eb
github.com/gin-gonic/gin.(*Engine).addRoute(0xc0000abba0, {0x1123c59, 0x4}, {0xc0002a6180, 0x2b}, {0xc0002a2030, 0x3, 0x3})
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:349 +0x252
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc00007e000, {0x1123c59, 0x4}, {0xc00057e240?, 0x4?}, {0xc000298098, 0x1, 0xc00025e2f0?})
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/routergroup.go:89 +0x13e
github.com/gin-gonic/gin.(*RouterGroup).POST(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/routergroup.go:112
main.main()
	/tmp/signal-cli-rest-api-src/main.go:330 +0x3aeb
```

this happens with my own as well as your example plugin.

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by Kariton** [comment]
okay.
thats a problem when using k8s configmaps mounted as folder:
```
# find /plugins -name "*.def"
/plugins/..2025_06_28_23_37_10.486753148/alertmanager.def
/plugins/alertmanager.def
```


e.g.
```yaml
          volumeMounts:
            - mountPath: /home/.local/share/signal-cli
              name: data
              subPath: data
            - mountPath: /plugins
              name: plugins
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: signal-cli-rest-api-data
        - configMap:
            defaultMode: 420
            name: alertmanager
          name: plugins
```

changing it to direct file mounts works:

```yaml
          volumeMounts:
            - mountPath: /home/.local/share/signal-cli
              name: data
              subPath: data
            - mountPath: /plugins/alertmanager.def
              name: plugins
              subPath: alertmanager.def
            - mountPath: /plugins/alertmanager.lua
              name: plugins
              subPath: alertmanager.lua
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: signal-cli-rest-api-data
        - configMap:
            defaultMode: 420
            name: alertmanager
          name: plugins
```
