### ISSUE TITLE
Run rootless

### ISSUE THREAD

**Issue by simbelmas** [bbernhard/signal-cli-rest-api#73]
Do you plan to make the api run rootless to allow execution on restricted kubernetes/openshift platform?

**Comment by bbernhard** [comment]
It already runs rootless (see https://github.com/bbernhard/signal-cli-rest-api/blob/master/entrypoint.sh#L22). Unfortunately it wasn't possible to use Dockerfile's `USER` mechanism as this would have broken existing setups

**Comment by simbelmas** [comment]
yes i saw that the api itself runs rootless.
I understand that using USER directive could lead to issues with existing setups.

**Comment by leonghui** [comment]
There is a way to run the container non-root using the USER directive by bypassing the entrypoint script. I have tested the example below with the `native` mode. With this method, the flags `cap_drop = ALL` and `security-opt = no-new-privileges` work too.
```
version: "3"
services:
  signal-cli-rest-api:
    entrypoint: /bin/sh
    command: -c "signal-cli-rest-api -signal-cli-config=$${SIGNAL_CLI_CONFIG_DIR}"
    container_name: signal-api
    environment:
      SIGNAL_CLI_CONFIG_DIR: /datastore
      MODE: native
    image: bbernhard/signal-cli-rest-api:latest
    user: 1001:1001
    volumes:
      - "/signal-cli-config:/datastore:rw"
```
